Use UI toolkit for variable table
jupyterlab-contrib/jupyterlab-variableInspector pull request #291
Opened 2023-11-24 05:55 UTC by kentarolim10

# Description
- Uses jupyter-ui-toolkit for the table styling

Pr for #277

2023-12-06 08:56 UTC, fcollonval requested changes
Thanks @kentarolim10 

Here are some suggestions. And in addition to those there is one point that needs to be addressed:

Could you please add the following statement in the `variableinspector` plugin (in index.ts):

```ts
addJupyterLabThemeChangeListener();
```

This will link the toolkit theme with the JupyterLab theme.

2023-12-06 08:56 UTC, fcollonval commented on src/variableinspector.ts
> +provideJupyterDesignSystem().register(allComponents);
You should import the `jp...` variant of the components.

Then could import as fine grain the proper components to optimize what is loaded:

```suggestion
provideJupyterDesignSystem().register(jpDataGrid(), jpDataGridRow(), ...);
```

2023-12-06 08:56 UTC, fcollonval commented on src/variableinspector.ts
> +
Dead code?

```suggestion
```

2023-12-06 08:56 UTC, fcollonval commented on style/base.css
The rule `.filter-type` should be removed

2023-12-06 08:56 UTC, fcollonval commented on src/variableinspector.ts
> +          console.log('Click on ' + item.varName);
Let's remove this

```suggestion
```

2023-12-06 08:56 UTC, fcollonval commented on src/variableinspector.ts
>          const ico = searchIcon.element();
Would you mind using a `jp-button` to wrap the icon in it (you can use the appearance _stealth_)?

2023-12-06 08:56 UTC, fcollonval commented on src/variableinspector.ts
>        const ico = closeIcon.element();
Could you wrap this icon in a `jp-button` with appearance _stealth_?

2023-12-06 08:56 UTC, fcollonval commented on src/variableinspector.ts
> +// const TABLE_BODY_CLASS = 'jp-VarInspector-content';
Dead code?

```suggestion
```

2023-12-06 08:56 UTC, fcollonval commented on src/variableinspector.ts
> +    const input = document.createElement('jp-search') as Search;
The [jp-text-field](https://jupyterlab-contrib.github.io/jupyter-ui-toolkit/?path=/docs/components-text-field--documentation) will be more appropriate than the search component.

2023-12-06 16:38 UTC, kentarolim10 commented
@fcollonval I have made the request changes to the PR 👍

2023-12-07 08:08 UTC, fcollonval approved these changes
Thanks @kentarolim10

2023-12-07 08:08 UTC, merged